# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FyndStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'MBProgressHUD'
  pod 'Kingfisher'

  target 'FyndStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FyndStoreUITests' do
    # Pods for testing
  end

end
